# Generated by Django 3.0.6 on 2020-05-17 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
